### ISSUE TITLE
Verification does not examine release mode

### ISSUE THREAD

**Issue by apetcher-amazon** [awslabs/aws-lc-verification#49]
The build used by the SAW verification has -DCMAKE_BUILD_TYPE=Rel instead of -DCMAKE_BUILD_TYPE=Release. This results in the default build being verified instead of the release build.

**Comment by RyanGlScott** [comment]
See #49, which switches CMake to use `Release` settings for all proofs except RSA.

**Comment by apetcher-amazon** [comment]
Addressed by #51
